In [1]:
import torch
import torch.nn as nn

# Example sentence
tokens = ["The", "cat", "chased", "the", "mouse"]

# Simple token IDs for demonstration
token_ids = torch.tensor([0, 1, 2, 3, 4])

# Dimensions
vocab_size = 5
embedding_dim = 8
attention_dim = 4

# Token embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# Convert token IDs into embeddings
x = embedding(token_ids)

print("Input shape:", x.shape)

Input shape: torch.Size([5, 8])


In [2]:
W_Q = nn.Linear(embedding_dim, attention_dim)
W_K = nn.Linear(embedding_dim, attention_dim)
W_V = nn.Linear(embedding_dim, attention_dim)

Q = W_Q(x)
K = W_K(x)
V = W_V(x)

print("Q shape:", Q.shape)
print("K shape:", K.shape)
print("V shape:", V.shape)

Q shape: torch.Size([5, 4])
K shape: torch.Size([5, 4])
V shape: torch.Size([5, 4])


In [3]:
print("\nQuery:")
print(Q)

print("\nKey:")
print(K)

print("\nValue:")
print(V)


Query:
tensor([[ 0.2766,  0.5062,  0.7466, -0.9590],
        [ 0.7273,  0.7884,  0.7650, -0.1665],
        [ 0.8635,  0.9173,  0.8948, -1.3255],
        [-0.0858,  0.7568,  0.2165,  0.0469],
        [ 0.2471,  0.8182, -0.3543,  0.5486]], grad_fn=<AddmmBackward0>)

Key:
tensor([[ 0.7884,  0.0423,  0.1878,  0.1733],
        [ 0.0162, -0.8020,  0.2074, -0.1813],
        [ 0.9213,  0.2387, -0.2658, -0.4662],
        [-0.6334, -0.7163,  0.0527, -0.1227],
        [-0.9852, -0.4692,  0.2221, -0.4632]], grad_fn=<AddmmBackward0>)

Value:
tensor([[ 0.5472,  0.3970,  0.5786,  0.3066],
        [-0.1883,  0.0038,  0.8236,  0.1308],
        [ 0.9353,  0.1098, -0.0504, -0.3274],
        [ 0.4782,  0.5610,  0.6282,  0.6685],
        [-0.0246, -0.4176,  0.2489,  0.0900]], grad_fn=<AddmmBackward0>)
